# Generated by Django 4.0.4 on 2022-07-06 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updeated',
            new_name='updated',
        ),
    ]
