# Generated by Django 4.0.4 on 2022-07-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoria',
            new_name='category',
        ),
    ]
